version: 0.2

phases:
  install:
    commands:
      - echo "Installing Maven"
      - yum install -y maven

  build:
    commands:
      - echo "Building the WAR file"
      - mvn clean package

artifacts:
  files:
    - target/*.war
  discard-paths: yes