version: 0.2

phases:
  install:
    commands:
      - echo "Installing Maven"
      - yum install -y maven

  build:
    commands:
      - echo "Building the WAR file"
      - mvn clean package
      - echo "Checking for generated WAR file"
      - ls -la target

  post_build:
    commands:
      - echo "Uploading WAR file to S3"
      - aws s3 cp target/myapp.war s3://codepipeline-ap-south-1-595684731156/myapp.war

artifacts:
  files:
    - target/myapp.war
  discard-paths: yes
