version: 0.2

phases:
  install:
    commands:
      - echo "Installing Maven"
      - yum install -y maven

  build:
    commands:
      - echo "Building the WAR file"
      - mvn clean package
      - echo "Renaming WAR file for consistency"
      - mv target/myapp.war myapp.war

  post_build:
    commands:
      - echo "Copying WAR file to S3 bucket"
      - aws s3 cp myapp.war s3://codepipeline-ap-south-1-595684731156/myapp.war

artifacts:
  files:
    - myapp.war
