version: 0.2

phases:
  install:
    commands:
      - echo "Installing Maven"
      - yum install -y maven

  build:
    commands:
      - echo "Building the WAR file"
      - mvn clean package
      - echo "Renaming WAR file for consistency"
      - mv target/myapp.war myapp.war

artifacts:
  files:
    - myapp.war
  name: myapp.war
  discard-paths: yes
