version: 0.2

phases:
  install:
    commands:
      - echo "Installing Maven"
      - curl -s https://get.sdkman.io | bash
      - source ~/.sdkman/bin/sdkman-init.sh
      - sdk install maven

  build:
    commands:
      - echo "Building the WAR file"
      - mvn clean package
      - mv target/*.war myapp.war

  post_build:
    commands:
      - echo "Deployment complete"
